#!/usr/bin/env python3
"""Write the standalone image files `three.texture(path)` is tested against.

These are loose files rather than glTF payloads, because that is the path under
test: `Assets.load_texture_file` reads bytes off disk, decides what they are from
their first few, and hands the decoded image to the same `claim_texture` a glTF
image goes through. The generator is checked in beside its output for
`make_textured.py`'s reason — so what the binaries contain is readable rather
than being blobs nobody can inspect.

What each one is for:

  * `checker.png` — **byte-identical in content to the image embedded in
    `textured.glb`**, which is the whole point of it. Load the .glb and then this
    file and the texture count must stay at one: the content hash is over the
    decoded RGBA, so where the bytes came from is not supposed to matter. If
    these two ever drift apart, `a_loose_file_and_a_gltf_image_are_one_upload`
    stops testing anything and still passes, so the checker below is generated by
    calling into `make_textured.py` rather than by copying its code.
  * `green.jpg` — a JPEG, so the JPEG branch of `decode_by_signature` is
    exercised by something. Solid colour on purpose: JPEG is lossy and a
    checkerboard comes back smeared, while a flat fill survives the DCT nearly
    exactly and can be asserted on as a colour.
  * `mislabelled.png` — the JPEG above, under a PNG name. A file renamed by an
    export step or a download is an ordinary thing to be handed, and dispatching
    on the extension would report it corrupt rather than load it.
  * `not_an_image.png` — text under a PNG name, for the refusal.
  * `deep.png` — 16-bit, which `image.c3l` decodes and `Image.to_rgba` cannot
    narrow. Refused by name rather than rendered from the wrong bytes.

`green.jpg` needs a JPEG encoder and this repository has no Python imaging
library, so it goes through macOS's `sips`. That is the one step here that is not
pure Python, which is why the .jpg is checked in: regenerating is a developer
action on a Mac, and using the fixture is not.

Regenerate with:  python3 test/fixtures/make_texture_files.py
"""

import struct
import subprocess
import sys
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
# The import below would otherwise leave a __pycache__ beside the fixtures, which
# is not something anyone wants to see in `git status` after regenerating them.
sys.dont_write_bytecode = True
sys.path.insert(0, str(HERE))

# The checkerboard `textured.glb` embeds. Imported rather than reimplemented, so
# the two fixtures cannot drift into holding different pictures — which would
# leave the dedup test asserting on a coincidence.
from make_textured import png_checker  # noqa: E402


def chunk(tag: bytes, data: bytes) -> bytes:
    return (struct.pack(">I", len(data)) + tag + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))


def png_solid(size: int, rgb: tuple, bit_depth: int = 8) -> bytes:
    """A flat fill, at 8 or 16 bits per channel, RGB (colour type 2)."""
    rows = bytearray()
    for _ in range(size):
        rows.append(0)  # filter byte: None
        for _ in range(size):
            for c in rgb:
                if bit_depth == 16:
                    # PNG is big-endian, and the doubled byte keeps the value the
                    # same colour at either depth — so `deep.png` differs from an
                    # 8-bit fill in its depth and in nothing else.
                    rows += struct.pack(">H", c * 257)
                else:
                    rows.append(c)

    ihdr = struct.pack(">IIBBBBB", size, size, bit_depth, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(bytes(rows), 9))
            + chunk(b"IEND", b""))


def main() -> None:
    (HERE / "checker.png").write_bytes(png_checker())

    # 32x32 rather than 8x8: JPEG works in 8x8 blocks, and an image that is one
    # block wide makes it impossible to tell a decoder that handles blocks from
    # one that handles a single block.
    source = HERE / "green.png"
    output = HERE / "green.jpg"
    source.write_bytes(png_solid(32, (0, 200, 0)))
    try:
        subprocess.run(
            ["sips", "-s", "format", "jpeg", "-s", "formatOptions", "best",
             str(source), "--out", str(output)],
            check=True, capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError) as err:
        raise SystemExit(
            f"could not run sips to write {output.name}: {err}\n"
            "green.jpg is checked in, so this only matters when regenerating on a non-Mac."
        )
    finally:
        source.unlink(missing_ok=True)

    (HERE / "mislabelled.png").write_bytes(output.read_bytes())
    (HERE / "not_an_image.png").write_bytes(
        b"This is not a PNG. It is named like one so that the loader has to read its bytes.\n"
    )
    (HERE / "deep.png").write_bytes(png_solid(8, (0, 200, 0), bit_depth=16))

    for name in ("checker.png", "green.jpg", "mislabelled.png", "not_an_image.png", "deep.png"):
        print(f"{name}: {(HERE / name).stat().st_size} bytes")


if __name__ == "__main__":
    main()
